D1={
'ДОСЛІДЖЕННЯ РИНКУ ТА ПОЗИЦІОНУВАННЯ · ЖОВТЕНЬ 2026':'MARKET RESEARCH AND POSITIONING · OCTOBER 2026',
'Корейський':'Korean','рамен':'ramen','в Україні':'in Ukraine',
'ОБСЯГ РИНКУ · МИТНА БАЗА':'MARKET SIZE · CUSTOMS DATA',
'Скільки локшини ввозять в Україну':'How much noodle is imported into Ukraine',
'ОБСЯГ ІМПОРТУ, ТОНН':'IMPORT VOLUME, TONNES',
'2025 · січень–травень':'2025 · Jan–May','2026 · січень–травень':'2026 · Jan–May','2025 · увесь рік':'2025 · full year',
'ІНВОЙС, МЛН ДОЛАРІВ':'INVOICE VALUE, USD M',
'$1,02 млн':'$1.02 M','$3,20 млн':'$3.20 M',
'МИТНА БАЗА · ПОХОДЖЕННЯ':'CUSTOMS DATA · ORIGIN',
'Звідки їде локшина: усі напрямки ввозу':'Where the noodles come from: all import origins',
'Січень–травень 2026 · вага нетто, тонн · частка в загальному ввозі 838,5 т':'Jan–May 2026 · net weight, tonnes · share of total imports of 838.5 t',
'СТРУКТУРА ВВОЗУ, %':'IMPORT MIX, %','ПО КРАЇНАХ ПОХОДЖЕННЯ':'BY COUNTRY OF ORIGIN',
'В’єтнам':'Vietnam','Корея':'Korea','Румунія':'Romania','Велика Британія':'United Kingdom','Латвія':'Latvia','Чехія':'Czechia','Польща':'Poland','Інші країни разом':'All other countries','Усього':'Total',
'Митна база користувача, код УКТ ЗЕД 1902 30 10 00. «Інші країни» — одним рядком: розбивки за країнами в базі немає.':'Customs database, HS code 1902 30 10 00. "All other countries" is a single line: the database has no country split.',
'СЕГМЕНТАЦІЯ':'SEGMENTATION','Сегментація за способом приготування':'Segmentation by preparation method',
'РАМЕН У ПАКЕТІ · З БУЛЬЙОНОМ':'PACK RAMEN · WITH BROTH','РАМЕН У ПАКЕТІ · ІЗ СОУСОМ':'PACK RAMEN · WITH SAUCE','РАМЕН У СТАКАНІ':'CUP RAMEN',
'позицій · 46 %':'SKUs · 46 %','позицій · 34 %':'SKUs · 34 %','позицій · 20 %':'SKUs · 20 %',
'ВАГА':'WEIGHT','МЕДІАНА ЦІНИ ЗА ПАЧКУ':'MEDIAN PRICE PER PACK','ДІАПАЗОН ЦІН ПАЧКИ':'PACK PRICE RANGE','БРЕНДІВ':'BRANDS',
'95 грн':'95 ₴','106 грн':'106 ₴','104 грн':'104 ₴','67–209 грн':'67–209 ₴','72–198 грн':'72–198 ₴','34–195 грн':'34–195 ₴',
'102–144 г':'102–144 g','105–145 г':'105–145 g','62–120 г':'62–120 g',
'СЕГМЕНТ × ЦІНОВА СМУГА · ПОЗИЦІЙ, грн за пачку':'SEGMENT × PRICE BAND · SKUs, ₴ per pack',
'до 80':'under 80','УСЬОГО':'TOTAL',
'Пакет · з бульйоном':'Pack · with broth','41 SKU · медіана 95 грн':'41 SKUs · median 95 ₴',
'Пакет · із соусом':'Pack · with sauce','30 SKU · медіана 106 грн':'30 SKUs · median 106 ₴',
'Стакан':'Cup','18 SKU · медіана 104 грн':'18 SKUs · median 104 ₴',
'СЕГМЕНТ 1 · РАМЕН У ПАКЕТІ · З БУЛЬЙОНОМ':'SEGMENT 1 · PACK RAMEN · WITH BROTH',
'Пакет з бульйоном: найбільший сегмент':'Pack with broth: the largest segment',
'Основна частина корейської полиці: локшина й порошковий бульйон, вариться в каструлі.':'The core of the Korean shelf: noodles and powdered broth, cooked in a pot.',
'ПОЗИЦІЙ У СЕГМЕНТІ':'SKUs IN SEGMENT',
'6 брендів у 11 мережах.':'6 brands in 11 chains.','46 % усієї категорії.':'46 % of the whole category.',
'МЕДІАНА ПОЛИЦІ':'MEDIAN SHELF PRICE','Діапазон: 67–209 ₴.':'Range: 67–209 ₴.',
'ДОРОЖЧІ ЗА ЦІЛЬ 120 ₴':'PRICIER THAN 120 ₴ TARGET','7 з 41':'7 of 41','позицій сегмента.':'SKUs in the segment.',
'Дорожчі за 140,55 ₴ (зараз): 2.':'Pricier than 140.55 ₴ (now): 2.',
'ВАГА ПАЧКИ':'PACK WEIGHT','межі сегмента':'segment range','за зрізом 29.09.2026.':'as of 29 Sep 2026.',
'ХТО ТРИМАЄ СЕГМЕНТ · SKU НА БРЕНД':'WHO HOLDS THE SEGMENT · SKUs PER BRAND',
'ПОЗИЦІЙ ЗА ЦІНОВОЮ СМУГОЮ · ₴ ЗА ПАЧКУ':'SKUs BY PRICE BAND · ₴ PER PACK',
'ПРЕДСТАВНИКИ СЕГМЕНТА · ВІД НАЙДЕШЕВШОЇ ДО НАЙДОРОЖЧОЇ ПОЗИЦІЇ':'SEGMENT EXAMPLES · FROM CHEAPEST TO MOST EXPENSIVE',
'Ottogi · Yeul Ramen дуже гостра':'Ottogi · Yeul Ramen extra spicy',
'Ottogi · З сиром':'Ottogi · Cheese','Ottogi · Середньогостра':'Ottogi · Medium spicy',
'Samyang · Зі смаком морепродуктів':'Samyang · Seafood flavor','Nongshim · Зі спеціями':'Nongshim · Spicy seasoning',
'СЕГМЕНТ 1 · РАМЕН У ПАКЕТІ · З БУЛЬЙОНОМ   ·   41 ПОЗИЦІЙ':'SEGMENT 1 · PACK RAMEN · WITH BROTH   ·   41 SKUs',
'Пакет з бульйоном: каталог 1 з 4 — 68–85 грн':'Pack with broth: catalogue 1 of 4 — 68–85 ₴',
'СЕГМЕНТ 1 · РАМЕН У ПАКЕТІ · З БУЛЬЙОНОМ   ·   Варіння 4–5 хв · подається з бульйоном   ·   вага 102–144 г':'SEGMENT 1 · PACK RAMEN · WITH BROTH   ·   Cook 4–5 min · served in broth   ·   weight 102–144 g',
"O'Food · Кімчі Рамен локшина":"O'Food · Kimchi Ramen noodles","O'Food · Кімчі Рамен":"O'Food · Kimchi Ramen","O'Food · Сівід Рамен":"O'Food · Seafood Ramen","O'Food · Смак морепродуктів":"O'Food · Seafood flavor",
'Ottogi · Jin рамен гостра':'Ottogi · Jin Ramen spicy','Nongshim · Кімчі Рамьон':'Nongshim · Kimchi Ramyun',
'Пакет з бульйоном: каталог 2 з 4 — 88–98 грн':'Pack with broth: catalogue 2 of 4 — 88–98 ₴',
'Nongshim · Soon Veggie Ramyun овоч…':'Nongshim · Soon Veggie Ramyun veg…',
'Nongshim · Cham-Pong Ramyun з море…':'Nongshim · Cham-Pong Ramyun seaf…',
'Paldo · Hwa Ramyun з гострим пе…':'Paldo · Hwa Ramyun hot pep…',
'Paldo · Kokomen зі смаком курки…':'Paldo · Kokomen chicken flav…',
'Paldo · Зі смаком морепродуктів':'Paldo · Seafood flavor',
'Paldo · Spicy Zanmang Loopy з б…':'Paldo · Spicy Zanmang Loopy w/ s…',
'Paldo · Zanmang Loopy оригіналь…':'Paldo · Zanmang Loopy origi…',
'Otoki · Cheesy Ramen зі смаком…':'Otoki · Cheesy Ramen flavo…',
'Nongshim · AnSungTangMyun з грибам…':'Nongshim · AnSungTangMyun mushr…',
'Пакет з бульйоном: каталог 3 з 4 — 104–117 грн':'Pack with broth: catalogue 3 of 4 — 104–117 ₴',
'Nongshim · З морепродуктами гостра':'Nongshim · Seafood spicy','Paldo · З сиром':'Paldo · Cheese',
'Nongshim · Shin Ramyun зі смаком г…':'Nongshim · Shin Ramyun flavor sp…',
'Samyang · Макаронні вироби Samyan…':'Samyang · Pasta Samyan…',
'Samyang · Локшина зі смаком курки…':'Samyang · Noodles chicken flav…',
'Samyang · З сиром':'Samyang · Cheese','Ottogi · З кунжутом':'Ottogi · Sesame',
'Ottogi · Jin Jjambbong Ramen з м…':'Ottogi · Jin Jjambbong Ramen seaf…',
'Nongshim · З морепродуктами середн…':'Nongshim · Seafood medium sp…',
'Пакет з бульйоном: каталог 4 з 4 — 118–205 грн':'Pack with broth: catalogue 4 of 4 — 118–205 ₴',
'Samyang · Зі смаком сиру':'Samyang · Cheese flavor','Nongshim · З морепродуктами':'Nongshim · Seafood',
'Nongshim · Shin Ramyun з грибами':'Nongshim · Shin Ramyun mushroom',
'Nongshim · Shin Ramyun Tom Yum Том…':'Nongshim · Shin Ramyun Tom Yum…',
'Nongshim · Шин Рамен Black':'Nongshim · Shin Ramen Black',
'СЕГМЕНТ 1 · ДЕ ПРОДАЄТЬСЯ':'SEGMENT 1 · WHERE IT IS SOLD','Пакет з бульйоном: де продається':'Pack with broth: where it is sold',
'ПОЗИЦІЙ СЕГМЕНТА В МЕРЕЖІ':'SEGMENT SKUs IN THE CHAIN',
'Ашан':'Auchan','«Зараз»':'Zaraz','«Космос»':'Kosmos','«Таврія В»':'Tavria V','«Клас»':'Klass','«Восторг»':'Vostorg','«ЧудоМаркет»':'ChudoMarket','«Сільпо»':'Silpo',
'Національні мережі · 5':'National chains · 5','ЦІЛЬОВИЙ КАНАЛ':'TARGET CHANNEL','Регіональні мережі · 7':'Regional chains · 7','РЕГІОНАЛЬНИЙ ВХІД':'REGIONAL ENTRY',
'Без позицій сегмента · 6':'No segment SKUs · 6','ВІЛЬНА ПОЛИЦЯ':'OPEN SHELF',
'МегаМаркет':'MegaMarket','ЕКО':'EKO','Епіцентр':'Epicentr','«Торба»':'Torba','«Ідеал»':'Ideal',
}
