D2={
'СЕГМЕНТ 2 · РАМЕН У ПАКЕТІ · ІЗ СОУСОМ':'SEGMENT 2 · PACK RAMEN · WITH SAUCE',
'Пакет із соусом: 30 позицій, медіана 106 грн':'Pack with sauce: 30 SKUs, median 106 ₴',
'7 брендів у 12 мережах.':'7 brands in 12 chains.','34 % усієї категорії.':'34 % of the whole category.',
'Діапазон: 72–198 ₴.':'Range: 72–198 ₴.','11 з 30':'11 of 30','Дорожчі за 140,55 ₴ (зараз): 5.':'Pricier than 140.55 ₴ (now): 5.',
'Samyang · Tangle зі смаком вершко…':'Samyang · Tangle creamy flav…',
'Bibigo · Стір-фрай Рамен Spicy T…':'Bibigo · Stir-Fry Ramen Spicy T…',
'Paldo · Bibim Men в корейському…':'Paldo · Bibim Men Korean-sty…',
'Samyang · З сиром гостра':'Samyang · Cheese spicy','Samyang · Зі смаком курки гостра':'Samyang · Chicken flavor spicy',
'СЕГМЕНТ 2 · РАМЕН У ПАКЕТІ · ІЗ СОУСОМ   ·   30 ПОЗИЦІЙ':'SEGMENT 2 · PACK RAMEN · WITH SAUCE   ·   30 SKUs',
'Пакет із соусом: каталог 1 з 3 — 78–89 грн':'Pack with sauce: catalogue 1 of 3 — 78–89 ₴',
'СЕГМЕНТ 2 · РАМЕН У ПАКЕТІ · ІЗ СОУСОМ   ·   Варіння 4–5 хв · воду злити, змішати із соусом   ·   вага 105–145 г':'SEGMENT 2 · PACK RAMEN · WITH SAUCE   ·   Cook 4–5 min · drain water, mix with sauce   ·   weight 105–145 g',
'фото немає':'no photo',
'Paldo · Volcano Carbonara гостр…':'Paldo · Volcano Carbonara spic…',
'Paldo · Compaghetti локшина':'Paldo · Compaghetti noodles',
'Bibigo · Стір-фрай Рамен зі смак…':'Bibigo · Stir-Fry Ramen flavo…',
'Bibigo · Стір-фрай Рамен Курка б…':'Bibigo · Stir-Fry Ramen Chicken…',
'Bibigo · Стір-фрай Рамен Cheese…':'Bibigo · Stir-Fry Ramen Cheese…',
'Ottogi · Stir-Fry Рамен із сиром':'Ottogi · Stir-Fry Ramen with cheese',
'Ottogi · Stir-Fry Рамен із сиром…':'Ottogi · Stir-Fry Ramen with chee…',
'Пакет із соусом: каталог 2 з 3 — 89–123 грн':'Pack with sauce: catalogue 2 of 3 — 89–123 ₴',
'Nongshim · Stir Fry Шин Рамьойн го…':'Nongshim · Stir Fry Shin Ramyun sp…',
'Nongshim · Shin Ramyun Stir Fry зі…':'Nongshim · Shin Ramyun Stir Fry w…',
'Samyang · Chacharoni зі смаком чо…':'Samyang · Chacharoni black bea…',
'Paldo · Stir fried з куркою':'Paldo · Stir fried chicken',
'Samyang · Buldak Jjajang зі смако…':'Samyang · Buldak Jjajang flav…',
'Paldo · Volcano Carbonara куряча':'Paldo · Volcano Carbonara chicken',
'Paldo · Volcano Chicken з курко…':'Paldo · Volcano Chicken w/ chick…',
'Пакет із соусом: каталог 3 з 3 — 125–198 грн':'Pack with sauce: catalogue 3 of 3 — 125–198 ₴',
"Choi's · Карбон":"Choi's · Carbonara",
'Samyang · Buldak Рамен з гострою…':'Samyang · Buldak Ramen with hot…',
'Samyang · Зі смаком курки дуже го…':'Samyang · Chicken flavor extra ho…',
'Samyang · Гостра з сиром':'Samyang · Spicy cheese',
'Samyang · Tangle зі смаком часник…':'Samyang · Tangle garlic flavo…',
'СЕГМЕНТ 2 · ДЕ ПРОДАЄТЬСЯ':'SEGMENT 2 · WHERE IT IS SOLD','Пакет із соусом: де продається':'Pack with sauce: where it is sold',
'Регіональні мережі · 8':'Regional chains · 8','Без позицій сегмента · 5':'No segment SKUs · 5',
'СЕГМЕНТ 3 · РАМЕН У СТАКАНІ':'SEGMENT 3 · CUP RAMEN','Стакан: заливається окропом, без плити':'Cup: just add boiling water, no stove needed',
'4 брендів у 8 мережах.':'4 brands in 8 chains.','20 % усієї категорії.':'20 % of the whole category.',
'Діапазон: 34–195 ₴.':'Range: 34–195 ₴.','3 з 18':'3 of 18','Дорожчі за 140,55 ₴ (зараз): 3.':'Pricier than 140.55 ₴ (now): 3.',
'Samyang · Bulgogi Рамен':'Samyang · Bulgogi Ramen','Ottogi · Jin Ramen Гостра':'Ottogi · Jin Ramen Spicy',
'Nongshim · Shrimp в стакані':'Nongshim · Shrimp cup',
'Nongshim · Shin Red Super Spicy го…':'Nongshim · Shin Red Super Spicy…',
'Nongshim · Shin Cup локшина з гриб…':'Nongshim · Shin Cup noodles mushr…',
'СЕГМЕНТ 3 · РАМЕН У СТАКАНІ   ·   18 ПОЗИЦІЙ':'SEGMENT 3 · CUP RAMEN   ·   18 SKUs',
'Стакан: каталог 1 з 2 — 65–103 грн':'Cup: catalogue 1 of 2 — 65–103 ₴',
'СЕГМЕНТ 3 · РАМЕН У СТАКАНІ   ·   Залити окропом 3–4 хв · без плити   ·   вага 62–120 г':'SEGMENT 3 · CUP RAMEN   ·   Add boiling water 3–4 min · no stove   ·   weight 62–120 g',
'Samyang · Jjanang Рамен':'Samyang · Jjajang Ramen','Samyang · Кімчі':'Samyang · Kimchi',
'Nongshim · Шин Рамьон гостра сублі…':'Nongshim · Shin Ramyun spicy fr…',
'Стакан: каталог 2 з 2 — 105–195 грн':'Cup: catalogue 2 of 2 — 105–195 ₴',
'Nongshim · Cup Ramyun Shrimp гостра':'Nongshim · Cup Ramyun Shrimp spicy',
'Nongshim · Суп Neoguri з морепроду…':'Nongshim · Neoguri soup seafo…',
'Samyang · Buldak Hot Chicken сир':'Samyang · Buldak Hot Chicken cheese',
'ЗВЕДЕННЯ · БРЕНДИ × МЕРЕЖІ':'SUMMARY · BRANDS × CHAINS','Усі бренди в усіх мережах':'All brands in all chains',
'верхнє число — кількість позицій (SKU) бренду в мережі':'top number — brand SKU count in the chain',
'нижнє число — медіанна ціна пачки в ₴  ·  чим темніше, тим більше позицій':'bottom number — median pack price in ₴  ·  the darker the cell, the more SKUs',
'«Таврія»':'Tavria','«ЧудоМ.»':'ChudoM.','МЕРЕЖ':'CHAINS','МЕДІАНА, ₴':'MEDIAN, ₴',
'62–140 г':'62–140 g','70–145 г':'70–145 g','105–140 г':'105–140 g','67–130 г':'67–130 g','122–127 г':'122–127 g','120 г':'120 g','137,8 г':'137.8 g','131 г':'131 g','62–145 г':'62–145 g',
'Каталоги мереж (zakaz.ua) і «Сільпо», 29.09.2026. Клітинка = унікальні EAN × медіана цін по магазинах мережі. «Сільпо» — 4 позиції без EAN (3 Samyang, 1 Nongshim); 93 = 89 позицій з EAN + 4 «Сільпо». Вага — мін.–макс. пачки бренду.':'Chain catalogues (zakaz.ua) and Silpo, 29 Sep 2026. Cell = unique EANs × median price across the chain\'s stores. Silpo: 4 SKUs without EAN (3 Samyang, 1 Nongshim); 93 = 89 SKUs with EAN + 4 Silpo. Weight = min–max pack of the brand.',
'ФОРМАТ × ВАГА':'FORMAT × WEIGHT','Де насправді щільна полиця':'Where the shelf is really dense',
'Кількість позицій і медіанна ціна пачки за ваговими смугами':'SKU count and median pack price by weight band',
'Пакет':'Pack','ПОЗИЦІЙ У ВАГОВІЙ СМУЗІ':'SKUs IN WEIGHT BAND','МЕДІАННА ЦІНА ПАЧКИ, ₴':'MEDIAN PACK PRICE, ₴',
'40–90 г':'40–90 g','90–110 г':'90–110 g','110–125 г':'110–125 g','125–145 г':'125–145 g','145 г +':'145 g +',
'120 грн':'120 ₴','наші SKU:':'our SKUs:','112,5–131 г':'112.5–131 g',
'ВАГА НАШИХ SKU — РИНКОВА':'OUR SKU WEIGHT IS IN LINE WITH THE MARKET',
'112,5–131 г потрапляє у дві найщільніші смуги: 70 % усіх позицій ринку.':'112.5–131 g falls into the two densest bands: 70 % of all SKUs on the market.',
'ЦІНА НАШИХ SKU ПРОТИ ЦИХ СМУГ':'OUR SKU PRICE VS THESE BANDS',
'При полиці 120 грн наші SKU на 29 % дорожчі за медіану смуги 110–125 г (93 грн), при поточних 140,55 грн — на 51 %.':'At a 120 ₴ shelf price our SKUs are 29 % above the median of the 110–125 g band (93 ₴); at the current 140.55 ₴ they are 51 % above.',
'РИТЕЙЛ-АУДИТ · МЕРЕЖІ':'RETAIL AUDIT · CHAINS','Що з корейського рамену стоїть у мережах':'What Korean ramen is on shelf in the chains',
'Суцільна перевірка онлайн-каталогів 18 мереж, зріз 29.09.2026. SKU — унікальні позиції корейського рамену в каталозі мережі.':'Full check of the online catalogues of 18 chains, snapshot of 29 Sep 2026. SKU = unique Korean ramen listings in the chain catalogue.',
'ЦІНА ПАЧКИ, ₴: мін.–макс. (лінія) · медіана (мітка)':'PACK PRICE, ₴: min–max (line) · median (marker)',
'НАЦ.':'NAT.','РЕГІОН.':'REG.',
'МегаМаркет · Ultramarket · ЕКО · Епіцентр · «Ідеал» — 0 позицій у зрізі':'MegaMarket · Ultramarket · EKO · Epicentr · Ideal — 0 SKUs in the snapshot',
'МЕДІАНА':'MEDIAN',
'ДІРКА №1 · «СІЛЬПО»':'GAP #1 · SILPO',
'Найбільша мережа країни тримає 4 позиції. Полиця відкрита, але вхід там 90–199 ₴.':'The largest chain in the country carries 4 SKUs. The shelf is open, but entry prices there are 90–199 ₴.',
'ДІРКА №2 · П’ЯТЬ МЕРЕЖ З НУЛЕМ':'GAP #2 · FIVE CHAINS WITH ZERO',
'МегаМаркет, Ultramarket, ЕКО, Епіцентр, «Ідеал» — жодної позиції у зрізі.':'MegaMarket, Ultramarket, EKO, Epicentr, Ideal — no SKUs in the snapshot.',
'ОДИН ПОСТАЧАЛЬНИК НА ДВІ МЕРЕЖІ':'ONE SUPPLIER FOR TWO CHAINS',
'«Космос» і «Таврія В» — по 12 позицій; 12 із них збігаються за EAN.':'Kosmos and Tavria V — 12 SKUs each; all 12 match by EAN.',
'КАНАЛИ ПРОДАЖУ':'SALES CHANNELS','Де продається категорія і кому':'Where the category is sold, and to whom',
'Ліворуч — усі перевірені точки: де категорія є і скільки там позицій. Праворуч — хто туди приходить і чи це наш покупець.':'Left: every outlet checked — where the category is present and how many SKUs. Right: who shops there and whether they are our buyer.',
'ПЕРЕВІРЕНІ ТОЧКИ ПРОДАЖУ · ПОЗИЦІЙ У КОЖНІЙ':'OUTLETS CHECKED · SKUs IN EACH',
'ПРОДУКТОВІ МЕРЕЖІ · 18 ПЕРЕВІРЕНО · 13 МАЮТЬ РАМЕН':'GROCERY CHAINS · 18 CHECKED · 13 CARRY RAMEN',
'категорії немає':'category not listed',
'АЗІЙСЬКІ ФУДШОПИ · 5 ПЕРЕВІРЕНО · 3 З ЦІНАМИ':'ASIAN FOOD SHOPS · 5 CHECKED · 3 WITH PRICES',
'Суші Повар':'Sushi Povar','Тайякі Март':'Taiyaki Mart','цінових даних немає':'no price data',
'МАРКЕТПЛЕЙСИ · 4 ПЕРЕВІРЕНО · 1 З ЦІНАМИ':'MARKETPLACES · 4 CHECKED · 1 WITH PRICES',
'Продуктовий роздріб':'Grocery retail','МЕРЕЖІ НАЦІОНАЛЬНОГО ПОКРИТТЯ · 18 ПЕРЕВІРЕНО':'NATIONWIDE CHAINS · 18 CHECKED',
'13 мереж мають корейський рамен, 5 — жодної позиції. «Сільпо» — 4 позиції на всю мережу.':'13 chains carry Korean ramen, 5 carry none. Silpo has 4 SKUs across the whole chain.',
'ПОКУПЕЦЬ:  Масовий покупець · щоденне харчування':'BUYER:  Mass-market shopper · everyday food',
'Онлайн-маркетплейси':'Online marketplaces','УНІВЕРСАЛЬНІ МАЙДАНЧИКИ · 4 МАЙДАНЧИКИ':'GENERAL MARKETPLACES · 4 PLATFORMS',
'Prom · Rozetka · MAUDAU · Bigl. Ціни є лише з Prom: 24 пропозицій, медіана 116 ₴, мінімум 80 ₴.':'Prom · Rozetka · MAUDAU · Bigl. Prices only from Prom: 24 offers, median 116 ₴, minimum 80 ₴.',
'ПОКУПЕЦЬ:  Масовий покупець · планована закупівля':'BUYER:  Mass-market shopper · planned purchase',
'Азійські фудшопи':'Asian food shops','ВХІД':'ENTRY','СПЕЦІАЛІЗОВАНИЙ ФУДРІТЕЙЛ · 5 МАГАЗИНІВ':'SPECIALIST FOOD RETAIL · 5 STORES',
'OMG! Asia · Тайякі Март · Суші Повар · Asia Foods · Panda Asian. Ціни є з трьох: 42–175 ₴.':'OMG! Asia · Taiyaki Mart · Sushi Povar · Asia Foods · Panda Asian. Prices from three of them: 42–175 ₴.',
'ПОКУПЕЦЬ:  Покупець азійської кухні · знає категорію':'BUYER:  Asian-cuisine shopper · knows the category',
'Outdoor- і мілітарі-рітейл':'Outdoor and military retail','НЕ НАШ КАНАЛ':'NOT OUR CHANNEL',
'ТУРИСТИЧНІ ТА ВІЙСЬКОВІ МАГАЗИНИ · 0 ПОЗИЦІЙ':'HIKING AND MILITARY STORES · 0 SKUs',
'Рамену там немає: він потребує окропу й каструлі.':'No ramen there: it needs boiling water and a pot.',
'ПОКУПЕЦЬ:  Турист і військовий · автономне харчування':'BUYER:  Hiker and soldier · field rations',
'Мережі — каталоги zakaz.ua і «Сільпо» 29.09.2026. Фудшопи — сторінки категорій (Суші Повар, Asia Foods, Тайякі Март), Prom.ua — одна сторінка видачі, жовтень 2026; без наборів дорожче 250 ₴. Rozetka, MAUDAU, Bigl, OMG! Asia, Panda Asian цінових даних не дали.':'Chains: zakaz.ua and Silpo catalogues, 29 Sep 2026. Food shops: category pages (Sushi Povar, Asia Foods, Taiyaki Mart); Prom.ua: one results page, October 2026; bundles above 250 ₴ excluded. Rozetka, MAUDAU, Bigl, OMG! Asia and Panda Asian gave no price data.',
'КАНАЛИ · ЦІНИ':'CHANNELS · PRICES','Ціна пачки по каналах і наша поточна полиця':'Pack price by channel vs our current shelf price',
'Мін.–макс. (лінія), 25–75 % пропозицій (блок), медіана (риска) · ціна пачки, ₴ · смуги — наша поточна полиця у двох варіантах закупівлі':'Min–max (line), 25–75 % of offers (box), median (tick) · pack price, ₴ · bands = our current shelf price under the two purchase-price options',
'ПРОПОЗИЦІЙ':'OFFERS','ДО 120 ₴':'UP TO 120 ₴',
'Національні мережі':'National chains','5 мереж · Ашан, METRO, NOVUS…':'5 chains · Auchan, METRO, NOVUS…',
'Регіональні мережі':'Regional chains','8 мереж · Grono, Onde, «Космос»…':'8 chains · Grono, Onde, Kosmos…',
'фудшоп':'food shop','маркетплейс':'marketplace','ціль 120 ₴':'target 120 ₴','зараз · 33 палети':'now · 33 pallets','зараз · 6 палет':'now · 6 pallets',
'Мережі: каталоги 29.09.2026, медіана ціни позиції в мережі. Фудшопи й Prom.ua: сторінки категорій, жовтень 2026, без наборів дорожче 250 ₴. Смуги: Vegetable/Spicy/Beef/Chicken (нижня межа) і Gouda/Carbonara (верхня межа) за фінмоделлю, маржа 30 %.':'Chains: catalogues of 29 Sep 2026, median SKU price within the chain. Food shops and Prom.ua: category pages, October 2026, bundles above 250 ₴ excluded. Bands: Vegetable/Spicy/Beef/Chicken (lower bound) and Gouda/Carbonara (upper bound) per the financial model, 30 % margin.',
'КАНАЛИ · ЦІНОВІ РІВНІ':'CHANNELS · PRICE TIERS','Частка пропозицій за ціною пачки в кожному каналі':'Share of offers by pack price in each channel',
'Мережі — 89 SKU корейського рамену (пакети й стакани); фудшопи й Prom.ua — рамен зі сторінок категорій, без наборів. Числа в смугах — % пропозицій':'Chains: 89 Korean ramen SKUs (packs and cups); food shops and Prom.ua: ramen from category pages, no bundles. Numbers inside the bars = % of offers',
'до 100 ₴':'< 100 ₴','понад 140 ₴':'over 140 ₴','ПОЗ.':'SKUs','ЯКІ БРЕНДИ (ПОЗИЦІЙ)':'WHICH BRANDS (SKUs)',
'Samyang 28 · інші 16 · Paldo 15 · Nongshim 13':'Samyang 28 · others 16 · Paldo 15 · Nongshim 13',
'інші 18 · Paldo 3 · Nongshim 2':'others 18 · Paldo 3 · Nongshim 2',
'інші 10 · Samyang 7 · Ottogi 4 · Nongshim 3':'others 10 · Samyang 7 · Ottogi 4 · Nongshim 3',
'Мережі — унікальні позиції (EAN) за медіанною ціною в мережі, 29.09.2026; «Сільпо» — 4 позиції. Фудшопи й Prom.ua — сторінки категорій, жовтень 2026 (бренд визначено за назвою; «інші» — не корейські або без бренду).':'Chains: unique SKUs (EAN) at the chain median price, 29 Sep 2026; Silpo: 4 SKUs. Food shops and Prom.ua: category pages, October 2026 (brand identified from the product name; "others" = non-Korean or unbranded).',
}
