D3={
'ОКРЕМИЙ КОНКУРЕНТ · ЦІНА ПРОДАЖУ':'CASE STUDY · RETAIL PRICE',
'Choi’s у «Таврії В»: по чому продавали':'Choi’s at Tavria V: what it sold for',
'Той самий бренд SIAS уже стоїть на українській полиці. Три дати й три рівні цін — щоб порівняти з нашою ціллю та поточною моделлю.':'The same SIAS brand is already on a Ukrainian shelf. Three dates and three price levels, to compare with our target and the current model.',
'CHOI’S CARBONARA 131 Г · ЦІНА ЗА ПАЧКУ, ГРН':'CHOI’S CARBONARA 131 G · PRICE PER PACK, ₴',
'ЄС · dotasia.eu · акція €1,80':'EU · dotasia.eu · promo €1.80','92,2 грн':'92.2 ₴',
'ЄС · dotasia.eu · звичайна €2,20':'EU · dotasia.eu · regular €2.20','112,6 грн':'112.6 ₴',
'«Таврія В» · 29.09.2026':'Tavria V · 29 Sep 2026','125,20 грн':'125.20 ₴','«Космос» · 29.09.2026':'Kosmos · 29 Sep 2026',
'«Таврія В» · 05–06.10 (за V3)':'Tavria V · 5–6 Oct (per V3)','131,50 грн':'131.50 ₴',
'НАШ SIAS · ціль за моделлю':'SIAS · model target','120,00 грн':'120.00 ₴',
'НАШ SIAS · зараз, 33 палети':'SIAS · now, 33 pallets','162,18 грн':'162.18 ₴',
'НАШ SIAS · зараз, 6 палет':'SIAS · now, 6 pallets','208,43 грн':'208.43 ₴',
'ПОРІВНЯННЯ · «ЗАРАЗ» = 33 ПАЛЕТИ, МАРЖА 30 %':'COMPARISON · "NOW" = 33 PALLETS, 30 % MARGIN',
'ЦІЛЬ 120':'TARGET 120','ЗАРАЗ':'NOW','Ціна, грн':'Price, ₴','До Choi’s 125,20':'vs Choi’s 125.20','До медіани пакета 102,8':'vs pack median 102.8',
'Дорожчих у категорії*':'Pricier SKUs in category*','13 з 71':'13 of 71','18 з 71':'18 of 71','3 з 71':'3 of 71',
'КОНКУРЕНТИ · ПОПУЛЯРНІ ПАКЕТИ':'COMPETITORS · POPULAR PACKS','Популярні пакети: кожна позиція та її ціна':'Popular packs: every SKU and its price',
'смуга: ціль 120 → зараз 33 палети → 6 палет':'band: target 120 → now 33 pallets → 6 pallets',
'ПАКЕТ 120 Г · 22 ПОЗИЦІЙ':'120 G PACK · 22 SKUs','68–128 ₴ · до 120 ₴ включно: 20':'68–128 ₴ · up to 120 ₴ inclusive: 20',
'Nongshim · зі спеціями':'Nongshim · spicy seasoning','Ottogi · Jin гостра':'Ottogi · Jin spicy','Nongshim · Кімчі':'Nongshim · Kimchi',
'Ottogi · Stir-Fry із сиром':'Ottogi · Stir-Fry with cheese','Paldo · Hwa Ramyun з гострим перцем':'Paldo · Hwa Ramyun hot pepper',
'Paldo · Kokomen зі смаком курки го…':'Paldo · Kokomen chicken flavor sp…','Ottogi · середньогостра':'Ottogi · medium spicy',
'Paldo · зі смаком морепродуктів':'Paldo · seafood flavor','Otoki · Cheesy Ramen зі смаком сир…':'Otoki · Cheesy Ramen cheese flav…',
'Nongshim · з морепродуктами гостра':'Nongshim · seafood spicy','Samyang · зі смаком морепродуктів':'Samyang · seafood flavor',
'Nongshim · Shin Ramyun зі смаком гост…':'Nongshim · Shin Ramyun spicy flav…','Samyang · Ramen з сиром':'Samyang · Ramen cheese',
'Nongshim · з морепродуктами середньог…':'Nongshim · seafood medium sp…',
'SIAS · Vegetable/Spicy/Beef/Chicken 113 г':'SIAS · Vegetable/Spicy/Beef/Chicken 113 g',
'ціль 120 ₴  ·  зараз: 33 палети 141 ₴  ·  6 палет 181 ₴':'target 120 ₴  ·  now: 33 pallets 141 ₴  ·  6 pallets 181 ₴',
'SIAS · Gouda Cheese 123 г':'SIAS · Gouda Cheese 123 g',
'ціль 120 ₴  ·  зараз: 33 палети 162 ₴  ·  6 палет 208 ₴':'target 120 ₴  ·  now: 33 pallets 162 ₴  ·  6 pallets 208 ₴',
'ПАКЕТ 130 Г · 9 ПОЗИЦІЙ':'130 G PACK · 9 SKUs','89–205 ₴ · до 120 ₴ включно: 6':'89–205 ₴ · up to 120 ₴ inclusive: 6',
'Ottogi · Stir-Fry із сиром гостра':'Ottogi · Stir-Fry cheese spicy','Paldo · Bibim Men в корейському ст…':'Paldo · Bibim Men Korean-sty…',
'Ottogi · Jin Jjambbong Ramen з море…':'Ottogi · Jin Jjambbong Ramen seaf…','Samyang · Ramen з сиром гостра':'Samyang · Ramen cheese spicy',
'SIAS · Carbonara Spicy 131 г':'SIAS · Carbonara Spicy 131 g','Samyang · гостра з сиром':'Samyang · spicy cheese','Nongshim · Шин Black':'Nongshim · Shin Black',
'ПАКЕТ 140 Г · 6 ПОЗИЦІЙ':'140 G PACK · 6 SKUs','103–138 ₴ · до 120 ₴ включно: 3':'103–138 ₴ · up to 120 ₴ inclusive: 3',
'Samyang · Chacharoni зі смаком чорни…':'Samyang · Chacharoni black bea…','Samyang · Buldak Jjajang зі смаком г…':'Samyang · Buldak Jjajang flavo…',
'Paldo · Volcano Chicken з куркою д…':'Paldo · Volcano Chicken w/ chick…','Samyang · зі смаком курки дуже гостра':'Samyang · chicken flavor extra hot',
'Samyang · зі смаком курки гостра':'Samyang · chicken flavor spicy',
'Каталоги мереж 29.09.2026: медіанна ціна пачки по мережах, де позиція є. Червона лінія — 120 ₴. SIAS: поточна полиця за фінмоделлю, маржа 30 %.':'Chain catalogues, 29 Sep 2026: median pack price across the chains where the SKU is listed. Red line = 120 ₴. SIAS: current shelf price per the financial model, 30 % margin.',
'КОНКУРЕНТИ · НИЖЧЕ 120 ₴':'COMPETITORS · BELOW 120 ₴','Ключові конкуренти продаються нижче 120 ₴':'Key competitors sell below 120 ₴',
'ДІАПАЗОН ЦІНИ ПАЧКИ ПО МЕРЕЖАХ, ₴':'PACK PRICE RANGE ACROSS CHAINS, ₴','дешевше за ціль 120 ₴':'below 120 ₴ target','дорожче за ціль':'above target',
'140 г · 10 мереж':'140 g · 10 chains','140 г · 6 мереж':'140 g · 6 chains','140 г · 7 мереж':'140 g · 7 chains',
'Samyang Buldak тушкована курка':'Samyang Buldak braised chicken','145 г · 7 мереж':'145 g · 7 chains',
'Nongshim Рамен зі спеціями':'Nongshim Ramen spicy seasoning','120 г · 7 мереж':'120 g · 7 chains','120 г · 9 мереж':'120 g · 9 chains',
'Samyang Buldak з сиром':'Samyang Buldak cheese','130 г · 9 мереж':'130 g · 9 chains','130 г · 3 мереж':'130 g · 3 chains','137 г · 7 мереж':'137 g · 7 chains',
'АКЦІЇ: ЗВИЧАЙНА ЦІНА → АКЦІЙНА, ₴':'PROMOS: REGULAR PRICE → PROMO PRICE, ₴','звичайна':'regular','акційна':'promo',
'Samyang Buldak курка та сир · 140 г':'Samyang Buldak chicken & cheese · 140 g',
'90 ₴  (−48 %) · «Сільпо»':'90 ₴  (−48 %) · Silpo','Samyang Buldak карбонара · 130 г':'Samyang Buldak carbonara · 130 g',
'Samyang · Ramen зі смаком курки з… · 135 г':'Samyang · Ramen chicken flav… · 135 g','108 ₴  (−39 %) · Ашан':'108 ₴  (−39 %) · Auchan',
'Samyang · зі смаком курки гостра · 140 г':'Samyang · chicken flavor spicy · 140 g','93 ₴  (−36 %) · «Торба»':'93 ₴  (−36 %) · Torba',
'Nongshim · Soon Veggie Ramyun овоч… · 112 г':'Nongshim · Soon Veggie Ramyun veg… · 112 g','74 ₴  (−23 %) · Ашан':'74 ₴  (−23 %) · Auchan',
'Ottogi · Jin Jjambbong Ramen з м… · 130 г':'Ottogi · Jin Jjambbong Ramen seaf… · 130 g','112 ₴  (−23 %) · Ашан':'112 ₴  (−23 %) · Auchan',
'Каталоги мереж 29.09.2026: ціна позиції в мережі (медіана по магазинах); «стара ціна» віддається не всіма мережами, тому акцій насправді більше. Смуги — наша поточна полиця: Vegetable/Spicy/Beef/Chicken (нижня межа) і Gouda/Carbonara (верхня).':'Chain catalogues, 29 Sep 2026: SKU price within the chain (median across stores); not all chains publish an "old price", so there are more promos than shown. Bands = our current shelf price: Vegetable/Spicy/Beef/Chicken (lower bound) and Gouda/Carbonara (upper).',
'ФІНМОДЕЛЬ · 33 ПАЛЕТИ · ФІНАЛЬНІ ЦИФРИ':'FINANCIAL MODEL · 33 PALLETS · FINAL FIGURES',
'33 палети: закупівля €0,65–0,75 → €0,54, полиця 120 ₴':'33 pallets: purchase €0.65–0.75 → €0.54, shelf 120 ₴',
'ЗАРАЗ · ПОЛИЦЯ':'NOW · SHELF PRICE',
'закупівля €0,65 / €0,75 · +17…35 % до цілі 120 ₴':'purchase €0.65 / €0.75 · +17…35 % above the 120 ₴ target',
'ЗАПИТ ДО SIAS':'REQUEST TO SIAS','−17 % / −28 % від теперішньої закупівлі (одна ціна для 6 SKU)':'−17 % / −28 % vs current purchase price (one price for all 6 SKUs)',
'ПІСЛЯ · ПОЛИЦЯ':'AFTER · SHELF PRICE',
'маржа 30 % · собівартість 38,53 ₴ · запас до 120 ₴: 0,14 ₴':'margin 30 % · landed cost 38.53 ₴ · headroom to 120 ₴: 0.14 ₴',
'Закупівля SIAS':'SIAS purchase','ціна пачки, €':'price per pack, €','Собівартість':'Landed cost','повна, в Україні':'full, in Ukraine',
'Ціна партнеру':'Partner price','СС ÷ 0,45':'cost ÷ 0.45','Бонус мережі':'Chain bonus','25 % ціни партнеру':'25 % of partner price',
'Наш прибуток':'Our profit','30 % ціни партнеру':'30 % of partner price','Націнка':'Markup','магазину · +40 %':'store · +40 %',
'ПОЛИЦЯ з ПДВ':'SHELF PRICE','партнеру × 1,40':'partner × 1.40 + VAT',
'ДО · 4 SKU':'BEFORE · 4 SKUs','Vegetable, Spicy, Beef, Chicken · закупівля €0,65':'Vegetable, Spicy, Beef, Chicken · purchase €0.65',
'ДО · 2 SKU':'BEFORE · 2 SKUs','Gouda, Carbonara · закупівля €0,75':'Gouda, Carbonara · purchase €0.75',
'ПІСЛЯ · запит SIAS':'AFTER · SIAS request','усі 6 SKU · закупівля €0,54':'all 6 SKUs · purchase €0.54',
'ЗМІНА · ПІСЛЯ − ДО (4 SKU)':'CHANGE · AFTER − BEFORE (4 SKUs)','ЗАКУПІВЛЯ SIAS ПО ПОЗИЦІЯХ · ЗАРАЗ → ЗАПИТ':'SIAS PURCHASE PRICE BY SKU · NOW → REQUEST',
'113 г':'113 g','112,5 г':'112.5 g','123 г':'123 g',
'Курс 51,20 ₴/€. Ціна партнеру = СС ÷ (1 − бонус 25 % − маржа 30 %), полиця = ціна партнеру × 1,40; усі ціни з ПДВ, за пачку. Собівартість «до» — з Self-Cost; «після» — за запитом €0,54. Джерело: RAMEN_FINMODEL_4_TABS, вкладка «Цена 120 грн — 33 паллет». Згоди SIAS немає — ціна для переговорів.':'Rate 51.20 ₴/€. Partner price = landed cost ÷ (1 − chain bonus 25 % − margin 30 %); shelf price = partner price × 1.40; all prices incl. VAT, per pack. "Before" landed cost per our cost file; "after" at the requested €0.54. Indicative model for discussion; the price has not been agreed.',
'ФІНМОДЕЛЬ · 6 ПАЛЕТ · ФІНАЛЬНІ ЦИФРИ':'FINANCIAL MODEL · 6 PALLETS · FINAL FIGURES',
'6 палет: закупівля €0,65–0,75 → €0,32, полиця 120 ₴':'6 pallets: purchase €0.65–0.75 → €0.32, shelf 120 ₴',
'закупівля €0,65 / €0,75 · +51…74 % до цілі 120 ₴':'purchase €0.65 / €0.75 · +51…74 % above the 120 ₴ target',
'−51 % / −57 % від теперішньої закупівлі (одна ціна для 6 SKU)':'−51 % / −57 % vs current purchase price (one price for all 6 SKUs)',
'маржа 30 % · собівартість 38,16 ₴ · запас до 120 ₴: 1,28 ₴':'margin 30 % · landed cost 38.16 ₴ · headroom to 120 ₴: 1.28 ₴',
'усі 6 SKU · закупівля €0,32':'all 6 SKUs · purchase €0.32',
'Курс 51,20 ₴/€. Ціна партнеру = СС ÷ (1 − бонус 25 % − маржа 30 %), полиця = ціна партнеру × 1,40; усі ціни з ПДВ, за пачку. Собівартість «до» — з Self-Cost; «після» — за запитом €0,32. Джерело: RAMEN_FINMODEL_4_TABS, вкладка «Цена 120 грн — 6 паллет». Згоди SIAS немає — ціна для переговорів.':'Rate 51.20 ₴/€. Partner price = landed cost ÷ (1 − chain bonus 25 % − margin 30 %); shelf price = partner price × 1.40; all prices incl. VAT, per pack. "Before" landed cost per our cost file; "after" at the requested €0.32. Indicative model for discussion; the price has not been agreed.',
'ЧУТЛИВІСТЬ':'SENSITIVITY','Яка закупівля потрібна при іншій полиці й іншій маржі':'Purchase price needed at other shelf prices and margins',
'Максимальна ціна закупівлі, €/пачку, за формулою вкладок «Цена 120 грн». Колір — порівняння з поточною ціною SIAS: €0,75 (Gouda, Carbonara) і €0,65 (решта).':'Maximum purchase price, € per pack, using the financial-model formula. Colour = comparison with the current SIAS price: €0.75 (Gouda, Carbonara) and €0.65 (the rest).',
'33 ПАЛЕТИ · ПОВНА МАШИНА':'33 PALLETS · FULL TRUCK','МАРЖА \\ ПОЛИЦЯ':'MARGIN \\ SHELF',
'105 грн':'105 ₴','110 грн':'110 ₴','130 грн':'130 ₴','140 грн':'140 ₴','6 ПАЛЕТ':'6 PALLETS',
'≥ €0,75 — досяжно для всіх SKU':'≥ €0.75 — achievable for all SKUs','€0,65–0,75 — для чотирьох SKU':'€0.65–0.75 — for four SKUs',
'€0,50–0,65 — потрібне зниження':'€0.50–0.65 — price reduction needed','< €0,50 — суттєве зниження':'< €0.50 — substantial reduction needed',
'Червона рамка — ціль: полиця 120 грн, маржа 30 %.':'Red frame = target: shelf price 120 ₴, margin 30 %.',
'Розрахунок за формулою H66 вкладок «Цена 120 грн» (курс 51,20; бонус 25 %; націнка 1,40; фінансування 2,5 %; ПДВ 20 %). Ціна вниз до євроцента.':'Calculated with the financial-model formula (rate 51.20; chain bonus 25 %; markup 1.40; financing 2.5 %; VAT 20 %). Price rounded down to the euro cent.',
}
